# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{orion6_plugin}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["O.S. Systems Softwares Ltda."]
  s.date = %q{2011-01-31}
  s.description = %q{Use this plugin to manage several features of the Henry Orion 6 eletronic timeclocks, like report creation, user management, configuration etc.}
  s.email = %q{contato@ossystems.com.br}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "app/controllers/application_controller.rb",
    "app/helpers/application_helper.rb",
    "app/views/layouts/application.html.erb",
    "config/application.rb",
    "config/database.yml",
    "config/environment.rb",
    "config/initializers/backtrace_silencers.rb",
    "config/initializers/inflections.rb",
    "config/initializers/mime_types.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/rep/orion6.rb"
  ]
  s.homepage = %q{http://www.ossystems.com.br/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Plugin to manage Henry Orion 6 eletronic timeclocks}
  s.test_files = [
    "test/performance/browsing_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.3"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.3"])
  end
end

